name: Daily Job Skill Extraction

on:
  workflow_dispatch:  # Enable manual trigger

jobs:
  extract-skills:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install spacy  # Install spaCy
          python -m spacy download en_core_web_lg

      # Step 4: Write Google Service Account JSON to a file
      - name: Write Google Service Account JSON
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

      # Step 5: Set up environment variables
      - name: Export environment variables
        run: |
          echo "GOOGLE_SERVICE_ACCOUNT_JSON=credentials.json" >> $GITHUB_ENV
          echo "THEIRSTACK_API_KEY=${{ secrets.THEIRSTACK_API_KEY }}" >> $GITHUB_ENV
          echo "GOOGLE_DOC_ID=${{ secrets.GOOGLE_DOC_ID }}" >> $GITHUB_ENV

      # Step 6: Run the Python script
      - name: Run the Python script
        run: |
          source .venv/bin/activate
          python main.py
